gui:
  language: en
  theme:
    selectedLineBgColor:
      - '#4b4873'
    selectedRangeBgColor:
      - '#4b4873'
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    externalDiffCommand: difft
os:
  open: alacritty -e nvim {{filename}}
  edit: nvim {{filename}}
  editAtLine: nvim {{filename}} +{{line}}
  editAtLineAndWait: nvim {{filename}} +{{line}}
  editInTerminal: true
